// packs render3d/out/* into assets/ (committed) and src/assets.js (generated, gitignored)
// ASSETS: name -> base64 image, REGIONS: name -> { object: {x,y,w,h} } in 1440x900 screen space
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const out = path.join(root, 'render3d', 'out');
const assets = {};
const regions = {};
for (const f of fs.readdirSync(out).sort()) {
  const ext = path.extname(f);
  const name = path.basename(f, ext);
  if (ext === '.jpg' || ext === '.png') {
    fs.copyFileSync(path.join(out, f), path.join(root, 'assets', f));
    assets[name] = fs.readFileSync(path.join(out, f)).toString('base64');
  } else if (ext === '.json') {
    regions[name] = JSON.parse(fs.readFileSync(path.join(out, f), 'utf8'));
  }
}
const js = '// generated by tools/build-assets.js\nconst ASSETS = ' + JSON.stringify(assets) + ';\nconst REGIONS = ' + JSON.stringify(regions) + ';\n';
fs.writeFileSync(path.join(root, 'src', 'assets.js'), js);
console.log('assets:', Object.keys(assets).join(', '));
console.log('src/assets.js', (js.length / 1e6).toFixed(2) + ' MB');
